/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tux0_Process */

#ifndef _Included_com_example_tux0_Process
#define _Included_com_example_tux0_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tux0_Process
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_tux0_Process_ConvertRGBtoGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
